name: eQuran
description: "Application for reading the Holy Quran"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.0+12
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.0
  quran: ^1.2.7
  vibration: ^1.8.4
  hive: ^2.2.3
  hive_flutter:
  hive_generator:
  build_runner:
  provider:
  adaptive_theme: ^3.6.0
  percent_indicator:
  numberpicker:
  like_button: ^2.0.5
  simple_gesture_detector: ^0.2.1
  flutter_svg: ^2.0.10+1
  audioplayers: ^6.4.0
  flutter_carousel_widget: ^2.2.0
  dynamic_height_grid_view: ^0.0.4
  scrollable_positioned_list: ^0.3.8
  expansion_tile_group: ^2.3.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  dependency_validator: ^4.0.0
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/index.json
    - assets/images/quran.svg

  fonts:
    - family: Hafs
      fonts:
        - asset: assets/fonts/Hafs.ttf
